workflows:
    graphql-workflow:
        name: Graphql Pipeline
        scripts:
          - name: CICD Started
            script: echo "Welcome to your CICD set up"
        publishing:
          email:
            recipients:
              - test@gmail.com
